# Read the documentation: https://symfony.com/doc/current/bundles/FOSCKEditorBundle/index.html

twig:
    form_themes:
        - '@FOSCKEditor/Form/ckeditor_widget.html.twig'

fos_ck_editor:
    configs:
        my_config:
            toolbar:
                - { name: "styles", items: ['Bold', 'Italic', 'Underline', '-', 'FontSize', 'NumberedList', 'BulletedList', '-', 'Blockquote', 'Link',] }
